### ISSUE TITLE
Period and exposure time and period combo boxes set correctly

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/reuss#17]
When starting up the exposure time and period are read from the detector but the combo boxes with ms, us, and ns are not set correctly. 

Example if the period is 2.5 us the value shown should be 2.5 and the combo box set to us.

**Comment by sudip70** [comment]
I implemented the changes but somehow it rounds the values. So i will push the changes after solving that bug

**Comment by sudip70** [comment]
I have created a new branch for this bug and pushed it. The value from the detector for nanoseconds and microseconds rounds may be because of multiplication or division. I think we can look at that issue tomorrow morning and merge the branch.

**Comment by erikfrojdh** [comment]
Works well now (using the nspython branch of the slsDetectorPackage).
