### ISSUE TITLE
Trigger mode

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/reuss#20]
Progress not working as expected

**Comment by erikfrojdh** [comment]
@thattil @sudip70 Update: it could actually be that the issue is on the g2panel. Maybe how I implemented the logic for updating progress and eventually stopping the receiver. 

Tested this morning with acquiring from a python script (play.py) and it was working fine in trigger mode as well.

**Comment by sudip70** [comment]
@erikfrojdh looks like the issue has been resolved as it ignores the frames in trigger mode and doesn't send the number of frames to the receiver. I will push the changes and add to PR
