### ISSUE TITLE
Setting number of frames in trigger mode

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/reuss#22]
When running in auto mode the number of frames is sent to both receiver and detector. In trigger mode we need to send number of triggers instead of number of frames. 

- Confirm that frames are ignored in trigger mode. 
- Send number of triggers instead of number of frames when selecting trigger

**Comment by sudip70** [comment]
@erikfrojdh . I have implemented the logic for this on g2panel. And it seems to be working fine. I will push this on timebug branch.
