### ISSUE TITLE
Viewer: get latency << 1s

### ISSUE THREAD

**Issue by tgruene** [slsdetectorgroup/reuss#37]
The latency of the viewer (in Vienna) is about 2s, i.e., when changing the beam,the viewer shows it about 2s later. Getting this below 1s, or even below 0.5s would make control much more convenient.
This is not very urgent, though, rather a convenience.

**Comment by erikfrojdh** [comment]
Solved by reducing the ZMQ_SNDBUF and ZMQ_RCVBUF buffer sizes
